/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DocsChar123SlugChar125RouteImport } from './routes/docs.{-$slug}'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminDomainsRouteImport } from './routes/admin/domains'
import { Route as AdminApiKeysRouteImport } from './routes/admin/api-keys'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth.verify-email'
import { Route as AuthSignUpRouteImport } from './routes/_auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth.sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthConsentRouteImport } from './routes/_auth.consent'
import { Route as Auth2faRouteImport } from './routes/_auth.2fa'
import { Route as DotwellKnownOpenidConfigurationRouteImport } from './routes/[.]well-known/openid-configuration'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as AdminOauthClientsRouteImport } from './routes/admin/oauth/clients'
import { Route as DotwellKnownOauthAuthorizationServerApiAuthRouteImport } from './routes/[.]well-known/oauth-authorization-server/api/auth'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DocsChar123SlugChar125Route = DocsChar123SlugChar125RouteImport.update({
  id: '/docs/{-$slug}',
  path: '/docs/{-$slug}',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDomainsRoute = AdminDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConsentRoute = AuthConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => AuthRoute,
} as any)
const Auth2faRoute = Auth2faRouteImport.update({
  id: '/2fa',
  path: '/2fa',
  getParentRoute: () => AuthRoute,
} as any)
const DotwellKnownOpenidConfigurationRoute =
  DotwellKnownOpenidConfigurationRouteImport.update({
    id: '/.well-known/openid-configuration',
    path: '/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOauthClientsRoute = AdminOauthClientsRouteImport.update({
  id: '/oauth/clients',
  path: '/oauth/clients',
  getParentRoute: () => AdminRoute,
} as any)
const DotwellKnownOauthAuthorizationServerApiAuthRoute =
  DotwellKnownOauthAuthorizationServerApiAuthRouteImport.update({
    id: '/api/auth',
    path: '/api/auth',
    getParentRoute: () => DotwellKnownOauthAuthorizationServerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/2fa': typeof Auth2faRoute
  '/consent': typeof AuthConsentRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/{-$slug}': typeof DocsChar123SlugChar125Route
  '/admin/': typeof AdminIndexRoute
  '/admin/oauth/clients': typeof AdminOauthClientsRoute
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/2fa': typeof Auth2faRoute
  '/consent': typeof AuthConsentRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/{-$slug}': typeof DocsChar123SlugChar125Route
  '/admin': typeof AdminIndexRoute
  '/admin/oauth/clients': typeof AdminOauthClientsRoute
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/_auth/2fa': typeof Auth2faRoute
  '/_auth/consent': typeof AuthConsentRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/{-$slug}': typeof DocsChar123SlugChar125Route
  '/admin/': typeof AdminIndexRoute
  '/admin/oauth/clients': typeof AdminOauthClientsRoute
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/2fa'
    | '/consent'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/admin/api-keys'
    | '/admin/domains'
    | '/admin/organizations'
    | '/admin/projects'
    | '/admin/users'
    | '/api/$'
    | '/docs/{-$slug}'
    | '/admin/'
    | '/admin/oauth/clients'
    | '/.well-known/oauth-authorization-server/api/auth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/2fa'
    | '/consent'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/admin/api-keys'
    | '/admin/domains'
    | '/admin/organizations'
    | '/admin/projects'
    | '/admin/users'
    | '/api/$'
    | '/docs/{-$slug}'
    | '/admin'
    | '/admin/oauth/clients'
    | '/.well-known/oauth-authorization-server/api/auth'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/admin'
    | '/sitemap.xml'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/_auth/2fa'
    | '/_auth/consent'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/verify-email'
    | '/admin/api-keys'
    | '/admin/domains'
    | '/admin/organizations'
    | '/admin/projects'
    | '/admin/users'
    | '/api/$'
    | '/docs/{-$slug}'
    | '/admin/'
    | '/admin/oauth/clients'
    | '/.well-known/oauth-authorization-server/api/auth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  DotwellKnownOpenidConfigurationRoute: typeof DotwellKnownOpenidConfigurationRoute
  ApiSplatRoute: typeof ApiSplatRoute
  DocsChar123SlugChar125Route: typeof DocsChar123SlugChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/docs/{-$slug}': {
      id: '/docs/{-$slug}'
      path: '/docs/{-$slug}'
      fullPath: '/docs/{-$slug}'
      preLoaderRoute: typeof DocsChar123SlugChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/domains': {
      id: '/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AdminDomainsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/consent': {
      id: '/_auth/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof AuthConsentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/2fa': {
      id: '/_auth/2fa'
      path: '/2fa'
      fullPath: '/2fa'
      preLoaderRoute: typeof Auth2faRouteImport
      parentRoute: typeof AuthRoute
    }
    '/.well-known/openid-configuration': {
      id: '/.well-known/openid-configuration'
      path: '/.well-known/openid-configuration'
      fullPath: '/.well-known/openid-configuration'
      preLoaderRoute: typeof DotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/oauth/clients': {
      id: '/admin/oauth/clients'
      path: '/oauth/clients'
      fullPath: '/admin/oauth/clients'
      preLoaderRoute: typeof AdminOauthClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-authorization-server/api/auth': {
      id: '/.well-known/oauth-authorization-server/api/auth'
      path: '/api/auth'
      fullPath: '/.well-known/oauth-authorization-server/api/auth'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerApiAuthRouteImport
      parentRoute: typeof DotwellKnownOauthAuthorizationServerRoute
    }
  }
}

interface AuthRouteChildren {
  Auth2faRoute: typeof Auth2faRoute
  AuthConsentRoute: typeof AuthConsentRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  Auth2faRoute: Auth2faRoute,
  AuthConsentRoute: AuthConsentRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AdminRouteChildren {
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminDomainsRoute: typeof AdminDomainsRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOauthClientsRoute: typeof AdminOauthClientsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminDomainsRoute: AdminDomainsRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOauthClientsRoute: AdminOauthClientsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DotwellKnownOauthAuthorizationServerRouteChildren {
  DotwellKnownOauthAuthorizationServerApiAuthRoute: typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
}

const DotwellKnownOauthAuthorizationServerRouteChildren: DotwellKnownOauthAuthorizationServerRouteChildren =
  {
    DotwellKnownOauthAuthorizationServerApiAuthRoute:
      DotwellKnownOauthAuthorizationServerApiAuthRoute,
  }

const DotwellKnownOauthAuthorizationServerRouteWithChildren =
  DotwellKnownOauthAuthorizationServerRoute._addFileChildren(
    DotwellKnownOauthAuthorizationServerRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRouteWithChildren,
  DotwellKnownOpenidConfigurationRoute: DotwellKnownOpenidConfigurationRoute,
  ApiSplatRoute: ApiSplatRoute,
  DocsChar123SlugChar125Route: DocsChar123SlugChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
