name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    uses: krakcons/krakstack/.github/workflows/project-deploy.yml@main
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      build_image: true
      build_context: .
      dockerfile: Dockerfile
      project_slug: krakstack-auth-prod
      krak_group: ka-app
      krak_task: auth
      vite_site_url: https://auth.krakstack.net
      vite_krakstack_auth_url: https://auth.krakstack.net
      vite_krakstack_auth_organization_id: SFriMuzEgwvtPV0acbQMLMmCW7pOIMGV
      vite_analytics_website_id: e0a42c9b-917b-4eb5-9645-599d6bcda74e
    secrets:
      KRAK_ADMIN_URL: ${{ secrets.KRAK_ADMIN_URL }}
      KRAK_RELEASE_TOKEN: ${{ secrets.KRAK_RELEASE_TOKEN }}
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
